INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('Samsung Galaxy S9',1);
INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('Samsung Galaxy S8',2);
INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('Motorola Nexus 6',1);
INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('Oneplus 9',1);
INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('Apple iPhone 13',1);
INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('Apple iPhone 12',1);
INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('Apple iPhone 11',1);
INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('iPhone X',1);
INSERT INTO PHONES_MASTER(PHONE_NAME, PHONE_QUANTITY) VALUES ('Nokia 3310',1);

INSERT INTO TESTERS(TESTER_ID, TESTER_NAME) VALUES (1,'John Smith');
INSERT INTO TESTERS(TESTER_ID, TESTER_NAME) VALUES (2,'Fatima Almeida');
INSERT INTO TESTERS(TESTER_ID, TESTER_NAME) VALUES (3,'Chen Li');

